version: '3'
services:
  nifi:
    image: apache/nifi
    ports:
      - 8443:8443
    environment:
      - NIFI-WEB-HTTP-PORT=8443
      - SINGLE_USER_CREDENTIALS_USERNAME=admin
      - SINGLE_USER_CREDENTIALS_PASSWORD=password
  nifi-registry:
    image: apache/nifi-registry
    ports:
      - 18080:18080
    mounts: 
      - /Users/nikunjkumarpatel/Applications/Nifi-registry:/opt/nifi-registry/nifi-registry-current/flow_storage
      - /Users/nikunjkumarpatel/Applications/providers.xml:/opt/nifi-registry/nifi-registry-current/conf/providers.xml